[package]
name = "maq_tic_tac_toe"
version = "0.1.0"
edition = "2021"

[package.metadata.android]
label = "MACROQUAD TIC-TAC-TOE"
min_sdk_version = 26

[dependencies]
macroquad = { git = "https://github.com/birhburh/macroquad.git", branch = "less_fps" }
